
def Toke():
    tokens = (
    'MAIS',
    'MENOS',
    'MULTIPLICACAO',
    'DIVISAO',
    'DOIS_PONTOS',
    'VIRGULA',
    'MENOR',
    'MAIOR',
    'IGUAL',
    'DIFERENTE',
    'MENOR_IGUAL',
    'MAIOR_IGUAL',
    'E_LOGICO',
    'OU_LOGICO',
    'NEGACAO',
    'ABRE_PARENTESE',
    'FECHA_PARENTESE',
    'ABRE_COLCHETE',
    'FECHA_COLCHETE',
    'SE',
    'ENTAO',
    'SENAO',
    'FIM',
    'REPITA',
    'ATE',
    'ATRIBUICAO',
    'LEIA',
    'ESCREVA',
    'RETORNA',
    'INTEIRO',
    'FLUTUANTE',
    'NUM_INTEIRO',
    'NUM_PONTO_FLUTUANTE',
    'NUM_NOTACAO_CIENTIFICA',
    'ID',
    )

    return tokens

